### ISSUE TITLE
multi-turn dialog format

### ISSUE THREAD

**Issue by LHolten** [microsoft/DialoGPT#17]
Section 3.1 of the paper states that dialog turns of the same session are concatenated into a long text, ended by the end-of-text token.

Does this mean that there are no special tokens in between dialog turns?

How do I separate dialog turns?

**Comment by dreasysnail** [comment]
There ARE special tokens (<|endoftext|>, id=50256) between dialogue turns in multi-turn setup. Your input format should be like this:

Turn1 <|endoftext|> Turn2 <|endoftext|> ... TurnN

Let us know if you have any further concerns.

**Comment by LHolten** [comment]
Thanks for the clarification, that makes sense.

**Comment by LHolten** [comment]
What are these `token_type_ids` for?
https://github.com/microsoft/DialoGPT/blob/5688864a8d3b4ede7ecaf832ea3c0443c3497e75/prepro.py#L107
It looks like they are different for the different turns in a session and get passed to the model while training.
This would be very weird as the GPT2 model from the transformers library converts `token_type_ids` as if they are regular `input_ids` and uses the same embedding for them.

**Comment by intersun** [comment]
Yes, they are different for different turns when we prepared the data. I believe we did some experiments about it, and end up using the default token_type_id (by setting token_type_id = None) during training.

**Comment by LHolten** [comment]
I see it now:
https://github.com/microsoft/DialoGPT/blob/5688864a8d3b4ede7ecaf832ea3c0443c3497e75/LSP_train.py#L279-L280

**Comment by ferdinando17** [comment]
> There ARE special tokens (<|endoftext|>, id=50256) between dialogue turns in multi-turn setup. Your input format should be like this:
> 
> Turn1 <|endoftext|> Turn2 <|endoftext|> ... TurnN

Hello,
 is the  <|endoftext|>  token separating turns the same as the token ending the session?

Thanks

**Comment by abisee** [comment]
> Turn1 <|endoftext|> Turn2 <|endoftext|> ... TurnN

@dreasysnail: should there be spaces around the <|endoftext|> or not?

**Comment by abisee** [comment]
@dreasysnail, was DialoGPT trained with any kind of padding (e.g., if the entire dialogue doesn't fill up the max length)? Or did the multi-turn dialogue always fill up the entire max length (as in GPT2 training)?
