### ISSUE TITLE
How does the model built from scratch compare to OpenAI GPT-2 fine-tuned?

### ISSUE THREAD

**Issue by AVancans** [microsoft/DialoGPT#19]
Also, what does BS inDialoGPT 345M (BS) mean?

**Comment by intersun** [comment]
Please refer to our arxiv paper at https://arxiv.org/pdf/1911.00536.pdf table 3 for more detailed results. It compared the results of training from scratch and fine-tuning from GPT2. 

Can you provide more context ? Most likely BS means either batch size or beam search in this project.

**Comment by AVancans** [comment]
@intersun Thank you - must have missed it. 

The BS I am referring to is from Evaluations table on Github Readme
<img width="190" alt="Screenshot 2019-11-25 at 14 07 31" src="https://user-images.githubusercontent.com/5124373/69516740-85ee1700-0f8d-11ea-91f5-e2feaac2f1da.png">

**Comment by intersun** [comment]
in this case it means beam search.
