### ISSUE TITLE
batch data in the right with 0, the results are far terrible.

### ISSUE THREAD

**Issue by zk31601102** [microsoft/DialoGPT#20]
why? @dreasysnail help !! ACL 2020!! cite your paper!!

**Comment by intersun** [comment]
> why? @dreasysnail help !! ACL 2020!! cite your paper!!

Thanks for your interests. 

To be honest we don't know how to generate in batch mode efficiently. Padding with some random token is not correct because it will change your input to "your_input_context !!!!!!!!!!!!!", assume "!" is your padded token. 

In our case we only put the tokens with same **token** length into one batch for generation, which could avoid any padding.

**Comment by dreasysnail** [comment]
If you must use a padding, you may use 50256 rather than 0. However padding the input generally harms the performance.

**Comment by zk31601102** [comment]
@intersun @dreasysnail Thanks a lot! I think I find the answer: padding harms the performance.
However in transformer package. the author always says: doesn't matter padding in the right since self-attention.

**Comment by intersun** [comment]
> @intersun @dreasysnail Thanks a lot! I think I find the answer: padding harms the performance.
> However in transformer package. the author always says: doesn't matter padding in the right since self-attention.

I don't know the exact context of your quote from transformer author, but I guess you could pad during the training since one could simply pad after "context + response". In other words, the input sequence will look like "context [SEP] response [SEP] **[PAD][PAD]**", which will not hurt the performance. While in your case, the input sequence look like "context **[PAD][PAD]**[SEP] ", which unfortunately will hurt the performance because the contexts are changed, and this sort of sequences were never seen during training.

**Comment by zk31601102** [comment]
> > @intersun @dreasysnail Thanks a lot! I think I find the answer: padding harms the performance.
> > However in transformer package. the author always says: doesn't matter padding in the right since self-attention.
> 
> I don't know the exact context of your quote from transformer author, but I guess you could pad during the training since one could simply pad after "context + response". In other words, the input sequence will look like "context [SEP] response [SEP] **[PAD][PAD]**", which will not hurt the performance. While in your case, the input sequence look like "context **[PAD][PAD]**[SEP] ", which unfortunately will hurt the performance because the contexts are changed, and this sort of sequences were never seen during training.

No! Our previous input format is: context [SEP]**[PAD], [PAD]** but the performance still awful.
So our current strategy is like input the sequences which have the same length as one batch. So the performance is great! We already half done the experiments! 
wait for our citation!hhhh 
Thanks again!

**Comment by intersun** [comment]
> > > @intersun @dreasysnail Thanks a lot! I think I find the answer: padding harms the performance.
> > > However in transformer package. the author always says: doesn't matter padding in the right since self-attention.
> > 
> > 
> > I don't know the exact context of your quote from transformer author, but I guess you could pad during the training since one could simply pad after "context + response". In other words, the input sequence will look like "context [SEP] response [SEP] **[PAD][PAD]**", which will not hurt the performance. While in your case, the input sequence look like "context **[PAD][PAD]**[SEP] ", which unfortunately will hurt the performance because the contexts are changed, and this sort of sequences were never seen during training.
> 
> No! Our previous input format is: context [SEP]**[PAD][PAD]** but the performance still awful.
> So our current strategy is like input the sequences which have the same length as one batch. So the performance is great! We already half done the experiments!
> wait for our citation!hhhh
> Thanks again!

That is what I am saying. The reason why your model performs worse is because you pad them like "context [SEP][PAD]"; while in the transformer package, pading means "context [SEP] response [SEP] [PAD]", and it will NOT hurt the performance.

Thanks!

**Comment by zk31601102** [comment]
> > > > @intersun @dreasysnail Thanks a lot! I think I find the answer: padding harms the performance.
> > > > However in transformer package. the author always says: doesn't matter padding in the right since self-attention.
> > > 
> > > 
> > > I don't know the exact context of your quote from transformer author, but I guess you could pad during the training since one could simply pad after "context + response". In other words, the input sequence will look like "context [SEP] response [SEP] **[PAD][PAD]**", which will not hurt the performance. While in your case, the input sequence look like "context **[PAD][PAD]**[SEP] ", which unfortunately will hurt the performance because the contexts are changed, and this sort of sequences were never seen during training.
> > 
> > 
> > No! Our previous input format is: context [SEP]**[PAD][PAD]** but the performance still awful.
> > So our current strategy is like input the sequences which have the same length as one batch. So the performance is great! We already half done the experiments!
> > wait for our citation!hhhh
> > Thanks again!
> 
> That is what I am saying. The reason why your model performs worse is because you pad them like "context [SEP][PAD]"; while in the transformer package, pading means "context [SEP] response [SEP] [PAD]", and it will NOT hurt the performance.
> 
> Thanks!

Yeah! I notice the difference, but during our experiments, we may not have the response to add. So I simply PAD the context. I really appreciate your timely and detailed response! 
I am gonna end the issue since the authors already solved it.
