### ISSUE TITLE
Path error when downloading reddit data

### ISSUE THREAD

**Issue by Craigie1996** [microsoft/DialoGPT#32]
Hi, thanks for the great work. When downloading  reddit data by "python demo.py --data small", it shows:
...
zcat: can't stat: data/out/train/conv/2009-11.tsv.gz (data/out/train/conv/2009-11.tsv.gz.Z): No such file or directory
zcat: can't stat: data/out/train/conv/2009-12.tsv.gz (data/out/train/conv/2009-12.tsv.gz.Z): No such file or directory
zcat: can't stat: data/out/train.tsv.gz (data/out/train.tsv.gz.Z): No such file or directory
error occurred, b"gzip: can't stat: ./train.tsv.gz (./train.tsv.gz.gz): No such file or directory\n"

Can you help fix the problem? Seems like it relates to line 67 of demo.py. Maybe we should  delete "cd .."?

**Comment by kushalchawla** [comment]
Hey. I am getting the same error. I want to download the data DialoGPT was trained on. Any advice how to do this without docker?
