### ISSUE TITLE
Do you have any Chinese language materials

### ISSUE THREAD

**Issue by sjyttkl** [microsoft/DialoGPT#37]
Do you have any Chinese language materials

**Comment by intersun** [comment]
We do not, but you could refer to [this project](https://github.com/yangjianxin1/GPT2-chitchat) for more details :)

**Comment by lemon234071** [comment]
> Do you have any Chinese language materials

https://github.com/lemon234071/GPT-Chinese

**Comment by sjyttkl** [comment]
tanks
