### ISSUE TITLE
"fs" vs "ft" model differences

### ISSUE THREAD

**Issue by hieudango** [microsoft/DialoGPT#39]
Hi, thanks very much for the repo. I am using the downloaded models: https://github.com/microsoft/DialoGPT/blob/master/demo_utils.py, and want to ask what are the differences between "medium_fs.pkl" vs "medium_ft.pkl", or "small_fs.pkl" vs "small_ft.pkl"? Do they impact the performance and accuracy of the model?

**Comment by dreasysnail** [comment]
Thanks for your interest. "fs" means "from scratch" and "ft" means "fine-tuned". The results from the "ft" model is typically better

**Comment by hieudango** [comment]
Thanks! I'll close the issue now
