### ISSUE TITLE
Downloading Reddit dataset small - make: wget: No such file or directory

### ISSUE THREAD

**Issue by haozhe-an** [microsoft/DialoGPT#60]
Hi,

When I tried to download the Reddit dataset (small), I encountered the following problem. 

`$ cd reddit_extractor; make -j 8; cd ..`

> wget https://files.pushshift.io/reddit/submissions/RS_v2_2005-12.xz -O data/reddit/RS_v2_2005-12.xz -o logs/RS_v2_2005-12.xz.log -c
> make: wget: No such file or directory
> wget https://files.pushshift.io/reddit/comments/RC_2005-12.bz2 -O data/reddit/RC_2005-12.bz2 -o logs/RC_2005-12.bz2.log -c
> make: wget: No such file or directory
> wget https://files.pushshift.io/reddit/submissions/RS_v2_2006-01.xz -O data/reddit/RS_v2_2006-01.xz -o logs/RS_v2_2006-01.xz.log -c
> make: wget: No such file or directory
> wget https://files.pushshift.io/reddit/comments/RC_2006-01.bz2 -O data/reddit/RC_2006-01.bz2 -o logs/RC_2006-01.bz2.log -c
> make: wget: No such file or directory
> make: *** [data/reddit/RC_2005-12.bz2] Error 1
> make: *** Waiting for unfinished jobs....
> make: *** [data/reddit/RS_2005-12.bz2] Error 1
> make: *** [data/reddit/RS_2006-01.bz2] Error 1
> make: *** [data/reddit/RC_2006-01.bz2] Error 1
> 

I'd like to download the dataset without training the model. Before running the make file, I installed the Conda environment listed in LSP-generic.yml without cudatoolkit=10.0.130=0 on a Mac. I checked reddit_extractor/logs/ but it is empty. Could someone help point out a possible direction to solve this problem? Thanks.

**Comment by haozhe-an** [comment]
Run `make -j 8` inside reddit_extractor seems to resolve this issue.

**Comment by muyeby** [comment]
Hi, @haozhe-an 

I also meet this problem, have you solved that? It seems that the links are no longer valid.

Thanks.

**Comment by DrMatters** [comment]
Hello, @muyeby !

Have you solved that?

Thanks

**Comment by muyeby** [comment]
Hi, @DrMatters 

I can't solve this problem，the links are no longer valid.

**Comment by FatCockHu** [comment]
I also meet this problem，for all the 'v2' files, we can not download them.

--2021-12-06 15:38:51--  https://files.pushshift.io/reddit/submissions/RS_v2_2006-03.xz
Resolving files.pushshift.io (files.pushshift.io)... 172.67.174.211, 104.21.55.251, 2606:4700:3032::ac43:aed3, ...
Connecting to files.pushshift.io (files.pushshift.io)|172.67.174.211|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-12-06 15:38:55 ERROR 404: Not Found.


--2021-12-06 15:46:16--  https://files.pushshift.io/reddit/submissions/RS_v2_2005-12.xz
Resolving files.pushshift.io (files.pushshift.io)... 172.67.174.211, 104.21.55.251, 2606:4700:3033::6815:37fb, ...
Connecting to files.pushshift.io (files.pushshift.io)|172.67.174.211|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-12-06 15:46:18 ERROR 404: Not Found.
