### ISSUE TITLE
Is there a gpt2-xl variant for DialoGPT?

### ISSUE THREAD

**Issue by pablogranolabar** [microsoft/DialoGPT#64]
Hi!

I have been using both gpt2-xl as well as DialoGPT with great results so far, thanks for making it available.

Question: is there a DialoGPT XL variant? As it appears only medium and large are in the transformers library.

TIA!

**Comment by dreasysnail** [comment]
Thanks for your interest. Unfortunately, we don't have any plan releasing a larger model than the existing ones. Sorry about that.
